### ISSUE TITLE
Image Optimization

### ISSUE THREAD

**Issue by takarushi** [itsmichaelwest/LumiaWOATestSite#1]
File sizes of images (~2MB) are quite big for the website and can potentially slow down load times on unstable or slow connections, consider using WebP or compressing the source files.
(Image Compression from Netlify's side may work, but, sometimes doesn't, so it's recommended to compress the images from source)

**Comment by itsmichaelwest** [comment]
Better compressed and WebP images are resolved in e22465d631822cef4a63b1b2f83d753bf989963e 😊
